services:
  mono-api:
    container_name: mono-api
    ports:
      - 8080:${PORT}
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app/server
    env_file:
      - .env
  mono-db:
    container_name: mono-db
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
  mono-redis:
    container_name: mono-redis
    build:
      context: ./redis
    volumes:
      - redisdata:/data

volumes:
  db-data:
  redisdata:
