services:
  mono-api:
    container_name: mono-api
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app/server
    env_file:
      - .env
  mono-db:
    container_name: mono-db
    image: postgres:16
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
