name: Test

on:
  workflow_call:
  workflow_dispatch:

env:
  db_host: localhost
  db_port: 5432
  db_user: postgres
  db_password: postgres
  db_name: mono-db
  db_url: postgres://postgres:postgres@postgres:5432/mono-db
  redis_host: localhost
  redis_port: 6379

jobs:
  test-go:
    name: Test go files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Download go modules
        run: go mod download
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.25.1
          policy_allow: true
      - name: Test go files
        run: |
          go clean -testcache
          gotestsum ./... -- -race -coverprofile=coverage.out
      - name: report coverage
        uses: k1LoW/octocov-action@v1
